### PR TITLE
Clarify voting rules accepted at NIAC2018

### PR DESCRIPTION
**Pull request by benajamin**
The wording applied in #6 is rather poor. The new text here should better represent the intent of the vote at NIAC2018

### CODE REVIEW

**Review by rayosborn — CHANGES_REQUESTED** [review]
This looks fine, but I'm not sure the preceding paragraph makes it clear that majority voting is allowed in the biennial meeting without two-thirds present.

**Comment by prjemian** [comment]
The preceding paragraph states:

> Topics voted on will require a simple majority unless specifically challenged by a committee member. 

How can this be changed to make it clear that majority voting is allowed?

**Comment by rayosborn** [comment]
It doesn't state the context of the voting, i.e., that it takes place in a biennial NIAC meeting.

**Review by rayosborn — APPROVED** [review]

**Comment by benajamin** [comment]
Approved by NIAC vote: https://github.com/nexusformat/NIAC/issues/71

**Pull request merged**
